"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from loguru import logger
from backend.interceptors import InterceptorHandler

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8s)@3vil8^qbs4as2l6_ps=pvyrf7befrmx0h%e-1$(ss4u0f*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

LOGGING_CONFIG = None
LOGURU_LOGGINGS = {
    'handlers': [
        {
            'sink': BASE_DIR / 'logs/debug.log',
            'level': 'DEBUG',
            'filter': lambda record: record['level'].no <= logger.level('DEBUG').no,
            'format': ("{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {name}: {function}:{line} - {message}"),
            'rotation': '1mb',
            'retention': '2 days',
            'compression': 'zip',
        },
        {
            'sink': BASE_DIR / 'logs/info.log',
            'level': 'INFO',
            'filter': lambda record: record['level'].no <= logger.level('INFO').no,
            'format': ("{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {name}: {function}:{line} - {message}"),
            'rotation': '1mb',
            'retention': '2 days',
            'compression': 'zip',
        },
        {
            'sink': BASE_DIR / 'logs/warning.log',
            'level': 'WARNING',
            'filter': lambda record: record['level'].no <= logger.level('WARNING').no,
            'format': ("{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {name}: {function}:{line} - {message}"),
            'rotation': '1mb',
            'retention': '2 days',
            'compression': 'zip',
        },
        {
            'sink': BASE_DIR / 'logs/error.log',
            'level': 'ERROR',
            'filter': lambda record: record['level'].no <= logger.level('ERROR').no,
            'format': ("{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {name}: {function}:{line} - {message}"),
            'rotation': '1mb',
            'retention': '2 days',
            'compression': 'zip',
            'backtrace': True,
            'diagnose': True
        },
        {
            'sink': BASE_DIR / 'logs/critical.log',
            'level': 'CRITICAL',
            'filter': lambda record: record['level'].no <= logger.level('CRITICAL').no,
            'format': ("{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {name}: {function}:{line} - {message}"),
            'rotation': '1mb',
            'retention': '2 days',
            'compression': 'zip',
        },
    ]
}

logger.configure(**LOGURU_LOGGINGS)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'loguru': {
            'class': 'backend.interceptors.InterceptorHandler',
        }
    },
    'root': {
        'handlers': ['loguru'],
        'level': 'DEBUG'
    }
}